;used procs outised the file
global printChar:proc,\
       printScore:proc,\
       printString:proc,\
       fillBackground:proc,\
       drawRectangle:proc,\
       drawGrid:proc,\
       drawMove:proc,\
       makeButton:proc,\
       playerTurn:proc,\
       changeTurn:proc,\
       announceInfo:proc,\
       drawlogo:proc

;constants
global grid:dword,\
       turnPiece:dword,\
       pieceDim:dword