;used procs outised the file
global	setVideoMode:proc,\
        terminateProcess:proc

;constants
global field:byte:70,\
       statusGrid: byte,\
       gridValues:byte,\
       rowInBetween:dword,\
       upperRightCorner:dword,\
       validateInput:byte,\
       rowSeparation:byte,\
       firstTop:dword,\
       horizontal:dword,\
       vertical:dword,\
       colors:word,\
       currentMenu:byte,\
       fieldType:byte,\
       playerColor:byte